//! Check the Paper III spectral algorithms against wcslib.
//!
//! These are NOT round-trip tests: a forward/inverse pair that shares a
//! sign error round-trips perfectly and is still wrong. The reference
//! values come from wcslib via astropy, generated by
//! `tests/data/gen_spectral_reference.py`.
//!
//! Three of the cases are the real KPNO `AWAV-GRA` spectrograph headers
//! printed in Paper III Figs. 3-5, which between them exercise a plain
//! grating, an echelle in 11th order, a true grism (`n_r`, `n'_r`), and
//! both signs of `CDELT` -- the sign that resolves the +/- ambiguity in
//! Paper III eq. (21).

use fitsy::Header;
use fitsy::wcs::Wcs;
use std::path::PathBuf;

struct Case {
    name: String,
    header: Header,
    /// Relative tolerance against wcslib, from the fixture.
    tol: f64,
    /// `(pixel, world)` pairs; pixels 0-based, world in the header's CUNIT.
    samples: Vec<(f64, f64)>,
}

fn load_cases() -> Vec<Case> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data/spectral_reference.txt");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut cases: Vec<Case> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.splitn(3, ' ');
        let tag = parts.next().expect("tag");
        let a = parts
            .next()
            .unwrap_or_else(|| panic!("malformed line: {line}"));
        // `CASE <name>` carries only two fields; every other tag has three.
        let mut third = || {
            parts
                .next()
                .unwrap_or_else(|| panic!("malformed line: {line}"))
        };
        match tag {
            "CASE" => cases.push(Case {
                name: a.to_string(),
                header: Header::empty(),
                tol: f64::NAN,
                samples: Vec::new(),
            }),
            "TOL" => cases.last_mut().expect("TOL before CASE").tol = a.parse().unwrap(),
            "KEYI" => {
                let c = cases.last_mut().expect("KEYI before CASE");
                c.header
                    .push(a, third().parse::<i64>().unwrap(), None)
                    .unwrap();
            }
            "KEYF" => {
                let c = cases.last_mut().expect("KEYF before CASE");
                c.header
                    .push(a, third().parse::<f64>().unwrap(), None)
                    .unwrap();
            }
            "KEYS" => {
                let c = cases.last_mut().expect("KEYS before CASE");
                c.header.push(a, third().to_string(), None).unwrap();
            }
            "DATA" => {
                let c = cases.last_mut().expect("DATA before CASE");
                c.samples
                    .push((a.parse().unwrap(), third().parse().unwrap()));
            }
            other => panic!("unknown tag `{other}` in {line}"),
        }
    }
    assert!(!cases.is_empty(), "no cases parsed from {}", path.display());
    cases
}

#[test]
fn fixture_parses() {
    let cases = load_cases();
    assert!(
        cases.len() >= 14,
        "expected the full fixture, got {}",
        cases.len()
    );
    for c in &cases {
        assert_eq!(c.samples.len(), 7, "{}: sample count", c.name);
        assert!(c.tol.is_finite(), "{}: missing TOL", c.name);
    }
}

#[test]
fn spectral_algorithms_match_wcslib() {
    let mut worst = 0.0_f64;
    let mut worst_case = String::new();
    for case in load_cases() {
        let wcs = Wcs::from_header(&case.header, ' ')
            .unwrap_or_else(|e| panic!("{}: parse failed: {e}", case.name))
            .unwrap_or_else(|| panic!("{}: no WCS in header", case.name));
        for &(pixel, want) in &case.samples {
            let got = wcs
                .pixel_to_world(&[pixel])
                .unwrap_or_else(|e| panic!("{}: pixel {pixel}: {e}", case.name))[0];
            // Relative: the cases span 5e-7 m to 6e14 Hz.
            let rel = (got - want).abs() / want.abs().max(f64::MIN_POSITIVE);
            if rel > worst {
                worst = rel;
                worst_case = format!("{} at pixel {pixel}", case.name);
            }
            assert!(
                rel < case.tol,
                "{}: pixel {pixel}: got {got:.12e}, wcslib {want:.12e} (rel {rel:.3e} \
                 exceeds {:.0e})",
                case.name,
                case.tol,
            );
        }
    }
    println!("worst relative deviation from wcslib: {worst:.3e} ({worst_case})");
}

/// The inverse must land back on the pixel wcslib started from, so a
/// forward transform that happens to match cannot hide a broken inverse.
#[test]
fn spectral_inverse_recovers_the_reference_pixel() {
    for case in load_cases() {
        let wcs = Wcs::from_header(&case.header, ' ').unwrap().unwrap();
        for &(pixel, world) in &case.samples {
            let got = wcs
                .world_to_pixel(&[world])
                .unwrap_or_else(|e| panic!("{}: world {world}: {e}", case.name))[0];
            assert!(
                (got - pixel).abs() < 1e-6,
                "{}: world {world:.12e} -> pixel {got}, expected {pixel}",
                case.name,
            );
        }
    }
}
